export const SET_JOB = 'set_job'
export const ADD_JOB = 'add_job'
export const DELETE_JOB = 'delete_job'
export const START_EDIT_JOB = 'start_edit_job'
export const EDITING_JOB = 'editing_job'
export const END_EDIT_JOB = 'end_edit_job'
